# Generated by Django 5.2.1 on 2025-05-26 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_artesanos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artesano',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='artesano',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
