# Generated by Django 5.2.1 on 2025-05-28 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_artesanos', '0003_carrito_itemcarrito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artesano',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
