# Generated by Django 5.2.1 on 2025-05-28 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_artesanos', '0004_alter_artesano_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='artesano',
            name='nombre_negocio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
